### ISSUE TITLE
UNCAUGHT TypeError: "list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by Lauriy** [andris9/Pangalink.net#1]
Had a tiny hiccup running the app on Ubuntu server 16.04 with Node 6.9.2:
```
Jan  3 04:16:29 Herbert pangalink-net[32479]: info [32479] HTTP ::ffff:127.0.0.1 [03/Jan/2017:09:16:29 +0000] "GET /et/projects HTTP/1.1" 200 - - 151.980 ms
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT TypeError: "list" argument must be an Array of Buffers
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at Function.Buffer.concat (buffer.js:314:13)
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at ServerResponse.res.end (/opt/pangalink-net/lib/forcecharset.js:39:30)
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at writeend (/opt/pangalink-net/node_modules/express-session/index.js:212:14)
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at Immediate.ontouch (/opt/pangalink-net/node_modules/express-session/index.js:291:11)
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at runCallback (timers.js:637:20)
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at tryOnImmediate (timers.js:610:5)
Jan  3 04:16:30 Herbert pangalink-net[32479]: ERR! [32479] UNCAUGHT     at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Since I know exactly nothing about Node, just went and did this at forcecharset.js:39:
```
if (buffer == '') {
    buffer = [new Buffer([])];
}
```

**Comment by andris9** [comment]
Which version/commit are you using? Does this error apply also to the code in master branch?

**Comment by Lauriy** [comment]
1.0.3, but I see master code differs from mine, has ES6 lets, etc. I have no motivation to upgrade to master right now though.

**Comment by andris9** [comment]
ok. I'm pretty sure this error does not apply to the current code.
